---
title: Category Turbulence
subtitle: Aging as Nullifying Process of Social Category
author:
  - name: Shingo Nitta
    corresponding: true
    email: nitta-shingo-sb@ynu.ac.jp
    affiliations:
      - name: Yokohama National University
        address: 79-1 Tokiwadai, Hodogaya-ku, Yokohama-shi
        city: Kanagawa
        postal-code: 240-0067
        country: Japan
date: today
# format: html
format:
  pdf:
    pdf-engine: pdflatex
    documentclass: article
    classoption:
      - 12pt
    include-in-header:
      - text: |
          \PassOptionsToPackage{x11names}{xcolor}
          \PassOptionsToPackage{authoryear,sort}{natbib}
          \usepackage{paper}
          \setlength{\bibhang}{2em}
          \setlength{\bibsep}{0.5em}
          \newcommand{\keywords}[1]{\vspace{0.5em}\noindent\textbf{Keywords:}~#1\par\vspace{1em}}
    keep-tex: false
    number-sections: false
    fig-pos: "t"
    colorlinks: false
    cite-method: natbib
    biblio-style: plainnat
lang: en
abstract: |
  How does age category intersect with other social categories, such as gender, race and ethnicity? Conventional studies conceptualize age as life course (???), but categorical view on age is less developed. In this article, I argue that age acts as *category turbulence*,  categorical characteristic that nullifies other category's ex-ante conditions, such as gender role and orderly bodies. <analyses say yes> I conclude incorporating people with old-age with a categorical perspective advances sociological debates on social categories and their intersectionality.
execute: 
  echo: false
bibliography: catturb.bib
---

## Acknowledgments {.appendix}

A replication package is available at github.com/sittaningo/replication/tree/main/XXX. When the paper is accepted, the replication package in gitub will be archived on Dataverse. [about data]. [appreciate feedbacks].

## Funding {.appendix}

This work was supported by JSPS KAKENHI Grant Numbers JP24KJ1919. 

## Conflict of Interest {.appendix}

None declared.

\keywords{social category, old-age, intersectionality}

# Introduction

One of the most well-documented concepts in sociology is social category. Social category, such as gender, race and ethnicity, divides and stratifies human beings, finally generating social inequality in a broader realm of society: labor market [@Goldin.2014hl3], family [@Mclanahan.2004j4] and health [@Case.2015]. Recently, scholars have paid more attention to intersectionality, which emphasizes on consolidation of social categories [@Collins.2015]. 

- TODO: Mclanahan SPEAKS TO RACE?

Going beyond examining categorical and intersectional inequality, a growing studies have begun to argue *how* social categories consolidate and shape hidden dimension of social inequality. For example, @Weisshaar.2024 coined the term "diversity values" in discrimination in hiring, that personnels value females as well as Black as the exchangeable and quantifiable social categories. @Monk.2021 found substantial heterogeneity among gender and racial disparity in wage by quantifying "bodily capital." As such, it advances sociological understandings of social categories to theorize a given social category can be actually conceptualize. <PARAPHRASE>

Contrary to the proliferation of gender and racial categories, age has hitherto existed as a haunting vacuum in studies of social categories. Age as social category has long-lasting attention in sociology [@Parsons.1942; @Linton.1942; @Neugarten.1965; @Riley.1972; @Settersten.1997; @Barrett.2022m3c]. But age is now collapsed into life course approach.<THINK MORE> As @Barrett.2022m3c [218] argues, "the most common approach was to examine some given process occurring over the life course, with scant attention to other dimensions of age, including age discrimination, ageism, or age identity." @Barrett.2022m3c foreshadows sociology of age and reconceptualizes age category as institution, performance and identity. However, @Barrett.2022m3c does not consider how age category intersects with gender and race.<THINK MORE>

In this article, I argue that old-age functions as *category turbulence* to other social categories such as gender and race. Category turbulence is defined as a categorical characteristic that nullifies other category's ex-ante conditions, such as gender role [@nanika] and orderly bodies [Peters.2025e3d]. Concretely, category turbulence occurs through two pathways: *positional* turbulence and *bodily* turbulence. *Positional* turbulence disrupts social expectations surrounding a social category. Men serves higher human capital than women because of division of labor [@Becker.1991]. Women have higher risks for paid leave for their familial obligation [@Arrow.1973]. Old-age men and women may be viewed as homogeneous due to ageism [@Roscigno.2007] and compositional change in human capital [@Autor.2009; @Sullivan.2010]. *Bodily* turbulence disrupts expectation of orderly bodies. For example, racial difference in skin tone may be in turmoil by wrinkle and stooped posture. In old age, social inequality in gender and race is no longer confirmed by category turbulence.

To address category turbulence, I carry out the survey expeiment in hiring.

Results show...

These results can support alternative conceptualization of age: *category turbulence*. To unlock the concept category turbluence goes beyond conceptualization of aging as cumulative process across the life course [@DiPrete.2006jp]. Rather, aging can be viewed as discrete transition [@Riley.1972], especially regarding transition from working-age (or prime-age) to old-age. Such discrete transition disavows *cues* of social category [@Monk.2022] through positional turbluence and bodily turbluence. <SEEMS TOO MUCH!>

## Aging as Continuous and Discrete Transition

In "A Sociology of Age Stratification," @Riley.1972 build age stratification theory, which organized elements of age structure and their generating process. Specifically, 

<!-- Arrow, K. J. (1973), "The Theory of Discrimination", in O. Ashenfelter and A. Rees (eds.), Discrimination in Labor Markets, Princeton, NJ: Princeton University Press. -->

# Data and Methods


# Results


# Discussion

